### ISSUE TITLE
Q: Validation in the ejs template

### ISSUE THREAD

**Issue by coaperator** [ZenitechSoftware/visa-js#8]
Hello!
I use express, passport and ejs template engine in my application
How can I check access to several (for example 10) functions in a template?
For example, I need to display a list of links for administering publications, such as creating, editing, moving, deleting, etc.
My template:
```
<ul>
	<li>Create</li>
	<li>Edit</li>
	<li>Move</li>
	<li>Delete</li>
</ul>
```
I understand correctly that if I need to check when and why to display this or that link, will I have to write such a check?
```
<% if(visa.ask(user.id).can.EditVisible.post()) { %>
<ul>
	<% if(visa.ask(user.id).can.Create.post()) { %>
	<li>Create</li>
	<% } %>

	<% if(visa.ask(user.id).can.Edit.post()) { %>
	<li>Edit</li>
	<% } %>

	<% if(visa.ask(user.id).can.Move.post()) { %>
	<li>Move</li>
	<% } %>

	<% if(visa.ask(user.id).can.Delete.post()) { %>
	<li>Delete</li>
	<% } %>
</ul>
<% } %>
```
and if I have 10 conditions, then will I have to write all of them into the IF condition?

**Comment by mykolasmolis** [comment]
Hi, sorry for delay. Your example makes sense. I am not an export of ejs, however, I think you will also need to pass `visa` as argument to ejs renderer (template).

**Comment by mykolasmolis** [comment]
Here is an example how to use `await` in ejs: https://stackoverflow.com/questions/60203249/ejs-async-true-with-node-express

Closing the issue.
